### PR TITLE
librato: Add batching

### PR DESCRIPTION
**Pull request by freeformz**
Batching is recommended behavior by Librato.

This also makes the requests to librato not drop metrics on retries, unless the
requests themselves can't be delivered. Currently a retry re-samples the metrics and looses any data previously sampled.

### CODE REVIEW

**Comment by freeformz** [comment]
I realized today that there is likely a bug in this.

**Comment by cyx** [comment]
Cool. Haven't deployed it, good to catch it early :)

**Comment by freeformz** [comment]
@cyx This is probably ready to test out now.

**Comment by freeformz** [comment]
@cyx Note, there are changes to the Error type, which now returns the dumped request.

**Pull request merged**
